name: PR Checks
on:
  - pull_request

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true
      - run: pnpm format:check
      - run: pnpm check
      - run: pnpm test
      - run: pnpm build
